# DESCRIPTION
# Takes a list of images presuably sorted by next most similar (`IMGlistByMostSimilar.txt`, which can be generated by the script `imgsGetSimilar.sh`), and presents an image viewer to navigate over the images in the order they are listed, and optionally discard any unwanted images in the sequence into a _discards subfolder.

# SOURCE
# This code of this script was written almost entirely by an AI in collaboration with a human (yours truly), with breathtaking exactness of what was requested (minus a few minor quickly fixed oversights). The conversation that developed it is at: https://chat.openai.com/share/095b6108-aa38-4687-9521-0b19773625af

# DEPENDENCIES
# Python with the tkinter library installed, a populated image file list `IMGlistByMostSimilar.txt` (or other file name; see comments of `imgsGetSimilar.sh`), and image files in that list in the same directory also.

# USAGE
# Call this script from python, with these parameters to Python and the script:
# - REQUIRED sys.argv[0] (for Python) : the path to this script; e.g:
#    /path/to/reduceIMGsimilarAssistant.py
# - OPTIONAL sys.argv[1] name of a text file which is a list of images ordered (for example by next most similar image). Such a file may be made by `imgsGetSimilar.sh` etc. If omitted, the script defaults to search for `IMGlistByMostSimilar.txt` in the directory your run this from, and assumes that is the list if it finds it. The images in the list file should be in the same directory.
# For example, to run this script without specifying the file name of the list of image comparisons, and use the default `IMGlistByMostSimilar.txt`:
#    python /path/to/reduceIMGsimilarAssistant.py
# Or if your comparison list file is named imageSorting01.txt, run:
#    python /path/to/reduceIMGsimilarAssistant.py imageSorting01.txt
# On launch, the script displays the first image in the list, with buttons to advance forward and backward through the list of images or delete them. Use the left arrow key or 'Back' button to navigate up (back) in the list, or the right arrow key or 'Forward' button to navigate forward in the list, and the 'Delete' key or button to move a viewed image into a _discards subfolder. Press F2 to rename the current image.

# CODE
import tkinter as tk
from tkinter import ttk
import os
import sys
import re
from PIL import Image, ImageTk

if len(sys.argv) > 1:       # positional parameter 1
    file_list = sys.argv[1]
    print('\nList file name (parameter 1) passed to script; using that:', file_list)
else:
    file_list = "IMGlistByMostSimilar.txt"
    print('\nNo list file name (parameter 1) passed to script; defaulted to:', file_list)

# Store the original list filename for later use when saving after deletions
original_list_file = file_list

# Initialize the main window
root = tk.Tk()
root.title("IMGlistByMostSimilar Reduce Assistant (list: " + file_list + ")")  # Updated window title

# Create a frame for the image and navigation buttons
frame = ttk.Frame(root)
frame.pack(fill=tk.BOTH, expand=True)

# Create a label for displaying the image
image_label = ttk.Label(frame)
image_label.pack(pady=10)  # Center with padding, no expansion

# Create labels for displaying the file name
file_label = ttk.Label(frame, text="")
file_label.pack(fill=tk.BOTH, expand=True)

# Create status bar
status_var = tk.StringVar()
status_var.set("Ready")
status_bar = ttk.Label(root, textvariable=status_var, relief=tk.SUNKEN, anchor=tk.W)
status_bar.pack(side=tk.BOTTOM, fill=tk.X)

# Define a subfolder for discarded images
discard_folder = "_discards"

# Helper function to update status bar
def update_status(message, is_error=False):
    status_var.set(message)
    if is_error:
        status_bar.config(foreground="red")
        root.after(3000, lambda: status_bar.config(foreground="black"))
    else:
        status_bar.config(foreground="black")
        root.after(5000, lambda: status_var.set("Ready"))

# Load image file list - parse by extracting content between single quotes
image_files = []
with open(original_list_file, "r") as file_handle:
    for line in file_handle:
        # Extract the filename between single quotes
        match = re.search(r"'([^']+)'", line)
        if match:
            image_files.append(match.group(1))

current_index = 0  # Current index of the displayed image

# Function to display the current image
def display_image(index):
   global current_index
   image_files_len = len(image_files)
   while True:
       if 0 <= index < len(image_files):
           current_index = index
           print_index = str(current_index + 1)
           image_file = image_files[current_index]
           if os.path.isfile(image_file):
               file_label.config(text=image_file + "\t(" + print_index + " of " + str(image_files_len) + ")")

               # Open the image using Pillow
               pil_image = Image.open(image_file)
               width, height = pil_image.size

               # Use consistent screen dimensions as reference (doesn't change between images)
               available_width = root.winfo_screenwidth() - 100
               available_height = root.winfo_screenheight() - 200

               # Calculate resize maintaining aspect ratio, never upscale
               width_ratio = available_width / width
               height_ratio = available_height / height
               scale_factor = min(width_ratio, height_ratio, 1.0)

               new_width = int(width * scale_factor)
               new_height = int(height * scale_factor)

               # Resize the image using Pillow
               resized_image = pil_image.resize((new_width, new_height), Image.LANCZOS)

               # Convert the PIL image to a Tkinter-compatible format
               tk_image = ImageTk.PhotoImage(resized_image)

               # Update the image label with the resized image
               image_label.config(image=tk_image)
               image_label.photo = tk_image
               image_label.update_idletasks()

               break
           else:
               image_files.remove(image_file)
               image_files_len = len(image_files)
       index += 1
       if index >= len(image_files):
           print("No valid images found.")
           break

# Function to navigate to the next image
def next_image():
    display_image(current_index + 1)

# Function to navigate to the previous image
def previous_image():
    display_image(current_index - 1)

# Function to delete the current image
def delete_image():
    # check for this folder on every discard attempt because I would rather not presume to create an empty subfolder on loading the script if I end up discarding nothing. (Even if this may end up causing redundant wasteful checks):
    if not os.path.exists(discard_folder):
        os.mkdir(discard_folder)
    global current_index
    if 0 <= current_index < len(image_files):
        image_file = image_files[current_index]
        discarded_path = os.path.join(discard_folder, os.path.basename(image_file))
        os.rename(image_file, discarded_path)
        del image_files[current_index]
        if current_index >= len(image_files):
            current_index = len(image_files) - 1
        display_image(current_index)
        # Update the original list file (not hardcoded)
        with open(original_list_file, "w") as file_handle:
            for image_file in image_files:
                file_handle.write(f"file '{image_file}'\n")
        
        # Report success
        success_msg = f"Moved to {discard_folder}: {image_file}"
        update_status(success_msg)
        print(success_msg)

# Function to rename the current image
def rename_image():
    global current_index
    if 0 <= current_index < len(image_files):
        old_name = image_files[current_index]
        base_name, extension = os.path.splitext(old_name)
        
        # Create custom dialog
        dialog = tk.Toplevel(root)
        dialog.title("Rename Image")
        dialog.transient(root)
        dialog.grab_set()
        
        # Create and pack widgets
        label = ttk.Label(dialog, text="Enter new name (without extension):")
        label.pack(pady=10)
        
        entry = ttk.Entry(dialog, width=40)
        entry.pack(pady=5)
        entry.insert(0, base_name)
        entry.icursor(tk.END)
        entry.focus_set()
        
        # Variables to store the result
        result = [None]
        should_close = [True]
        
        def show_error(message):
            error_dialog = tk.Toplevel(root)
            error_dialog.title("Rename Error")
            error_dialog.transient(root)
            error_dialog.grab_set()
            ttk.Label(error_dialog, text=message, foreground="red").pack(pady=20, padx=20)
            ttk.Button(error_dialog, text="OK", command=error_dialog.destroy).pack(pady=10)
            error_dialog.update_idletasks()
            x = root.winfo_x() + (root.winfo_width() // 2) - (error_dialog.winfo_width() // 2)
            y = root.winfo_y() + (root.winfo_height() // 2) - (error_dialog.winfo_height() // 2)
            error_dialog.geometry(f"+{x}+{y}")
            update_status(message, is_error=True)
            print(f"ERROR: {message}")
        
        def on_enter():
            new_base = entry.get().strip()
            if not new_base:
                show_error("Filename cannot be empty.")
                return
            
            # Validate filename characters
            invalid_chars = r'[<>:"/\\|?*]'
            if re.search(invalid_chars, new_base):
                show_error(f"Invalid characters in filename.\nCannot use: < > : \" / \\ | ? *")
                return
            
            result[0] = new_base
            should_close[0] = True
            dialog.destroy()
        
        def on_cancel():
            result[0] = None
            should_close[0] = True
            dialog.destroy()
        
        # Create button frame
        button_frame_widget = ttk.Frame(dialog)
        button_frame_widget.pack(pady=10)
        
        enter_button = ttk.Button(button_frame_widget, text="ENTER", command=on_enter)
        enter_button.pack(side=tk.LEFT, padx=5)
        
        cancel_button = ttk.Button(button_frame_widget, text="Cancel", command=on_cancel)
        cancel_button.pack(side=tk.LEFT, padx=5)
        
        # Bind keyboard events
        dialog.bind("<Return>", lambda event: on_enter())
        dialog.bind("<Escape>", lambda event: on_cancel())
        
        # Center the dialog
        dialog.update_idletasks()
        x = root.winfo_x() + (root.winfo_width() // 2) - (dialog.winfo_width() // 2)
        y = root.winfo_y() + (root.winfo_height() // 2) - (dialog.winfo_height() // 2)
        dialog.geometry(f"+{x}+{y}")
        
        # Wait for dialog to close
        root.wait_window(dialog)
        
        new_base = result[0]
        if new_base and new_base != base_name:
            new_name = new_base + extension
            old_path = old_name
            new_path = new_name
            
            # Check if target filename already exists
            if os.path.exists(new_path):
                show_error(f"'{new_path}' already exists.")
                return
            
            # Try to rename the actual file
            try:
                os.rename(old_path, new_path)
                print(f"File renamed: {old_name} -> {new_name}")
            except Exception as e:
                show_error(f"Failed to rename file:\n{e}")
                return
            
            # File rename succeeded. Now update text files and track results
            update_success = True
            results = []
            
            # Update the original list file
            try:
                with open(original_list_file, "w") as file_handle:
                    for image_file in image_files:
                        file_handle.write(f"file '{image_file}'\n")
                results.append(f"[OK] Updated {original_list_file}")
                print(f"[OK] Updated {original_list_file}")
            except Exception as e:
                update_success = False
                results.append(f"[FAIL] Failed to update {original_list_file}: {e}")
                print(f"[FAIL] Failed to update {original_list_file}: {e}")
            
            # Update imageDifferenceRankings.txt if it exists
            rankings_file = "imageDifferenceRankings.txt"
            if os.path.exists(rankings_file):
                try:
                    with open(rankings_file, "r") as file_handle:
                        rankings_content = file_handle.read()
                    updated_content = re.sub(re.escape(old_name), new_name, rankings_content)
                    with open(rankings_file, "w") as file_handle:
                        file_handle.write(updated_content)
                    results.append(f"[OK] Updated {rankings_file}")
                    print(f"[OK] Updated {rankings_file}")
                except Exception as e:
                    update_success = False
                    results.append(f"[FAIL] Failed to update {rankings_file}: {e}")
                    print(f"[FAIL] Failed to update {rankings_file}: {e}")
            else:
                results.append(f"[SKIP] {rankings_file} not found")
                print(f"[SKIP] {rankings_file} not found")
            
            # Update in-memory list
            image_files[current_index] = new_name
            
            # Refresh the display
            display_image(current_index)
            
            # Report cumulative results
            summary = f"Renamed: {old_name} -> {new_name}"
            if update_success:
                ok_results = [r for r in results if r.startswith("[OK]")]
                status_msg = summary + " | " + "; ".join(ok_results)
                update_status(status_msg)
                print(f"SUCCESS: {summary}")
            else:
                status_msg = summary + " (partial failure) | " + "; ".join(results)
                update_status(status_msg, is_error=True)
                print(f"PARTIAL FAILURE: {summary}")

# Create a separate frame for buttons to keep them at bottom
button_frame = ttk.Frame(root)
button_frame.pack(side=tk.BOTTOM, fill=tk.X)

# Create navigation buttons
previous_button = ttk.Button(button_frame, text="Back (left arrow key)", command=previous_image)
next_button = ttk.Button(button_frame, text="Forward (right arrow key)", command=next_image)
delete_button = ttk.Button(button_frame, text="Sort to _discards (delete key)", command=delete_image)
rename_button = ttk.Button(button_frame, text="Rename (F2)", command=rename_image)

previous_button.pack(side=tk.LEFT, padx=5, pady=5)
next_button.pack(side=tk.LEFT, padx=5, pady=5)
delete_button.pack(side=tk.LEFT, padx=5, pady=5)
rename_button.pack(side=tk.LEFT, padx=5, pady=5)

# Display the first image
display_image(current_index)

# Function to handle keypress events
def on_key(event):
    if event.keysym == "Left":  # Left arrow key
        previous_image()
    elif event.keysym == "Right":  # Right arrow key
        next_image()
    elif event.keysym == "Delete":  # Delete key
        delete_image()
    elif event.keysym == "F2":  # F2 key for rename
        rename_image()
    elif event.keysym == "Escape":  # Escape key
        sys.exit()

# Bind keypress events to the root window
root.bind("<Left>", on_key)
root.bind("<Right>", on_key)
root.bind("<Delete>", on_key)
root.bind("<F2>", on_key)
root.bind("<Escape>", on_key)

# Run the Tkinter main loop
root.mainloop()