# DESCRIPTION
# Last of a series of scripts designed to eliminate similar .hexplt format palettes. Moves palettes listed in paletteDifferencesBelowThreshold.txt (generated by listPaletteDifferencesBelowThreshold.sh, which you must run first) to a folder _palettes_proposed_to_delete_AYXqmYHefxMYzD for examination and possible deletion.

# USAGE
# Run listPaletteDifferencesBelowThreshold.sh (which tells you to run another script before it), to generate the list paletteDifferencesBelowThreshold.txt. Then run this script:
#  deletePalettesDifferentBelowThreshold.sh
# -- and follow the prompt (see echo statement at end of script) to decide whether to permanently delete proposed deleted files.


# CODE
arrayOfFilesToDelete=(`sed 's/.*|\(.*\)/\1/g' paletteDifferencesBelowThreshold.txt`)

NumberOfFilesInArray=${#arrayOfFilesToDelete[@]}

if [ ! -d _palettes_proposed_to_delete_AYXqmYHefxMYzD ]; then mkdir _palettes_proposed_to_delete_AYXqmYHefxMYzD; fi

for element in ${arrayOfFilesToDelete[@]}
do
	# echo element $element
	fileNameNoExtension=${element%.*}
	# only move to target dir if file does not exist there:
	if [ ! -e "./_palettes_proposed_to_delete_AYXqmYHefxMYzD/$element" ]
	then
		mv ./$element ./_palettes_proposed_to_delete_AYXqmYHefxMYzD/
	fi
	if [ ! -e "./_palettes_proposed_to_delete_AYXqmYHefxMYzD/$fileNameNoExtension.png" ]
	then
		mv ./$fileNameNoExtension.png ./_palettes_proposed_to_delete_AYXqmYHefxMYzD
	fi
done

echo "DONE. Have moved $NumberOfFilesInArray palettes and coressponding PNG palette renders below similarity threshhold $deletePalettesBelowDifferenceThreshold into temp dir _palettes_proposed_to_delete_AYXqmYHefxMYzD. Examine them, and if you wish to, delete them. (If you delete them, you may also want to delete paletteDifferencesBelowThreshold.txt, as that would be outdated after the delete. Also, you may wish to manually run allPalettesCompareCIECAM02.sh again, because the file it created, paletteDifferenceRankings.txt, would be outdated with those files gone."