stroke(255);
background(51);
color from = color(#B2DEFF);
color to = color(#FF00FF);
color interA = lerpColor(from, to, .14);
color interB = lerpColor(from, to, .28);
color interC = lerpColor(from, to, .42);
color interD = lerpColor(from, to, .57);
color interE = lerpColor(from, to, .71);
color interF = lerpColor(from, to, .85);
println(hex(interA));
println(hex(interB));
println(hex(interC));
println(hex(interD));
println(hex(interE));
println(hex(interF));
